config:
  target: "http://localhost:3000"
  phases:
    - duration: 10
      arrivalRate: 1
      name: Warm up
    - duration: 20
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 30
      arrivalRate: 10
      name: Sustained load
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
    thresholds:
      - http.response_time.p99: 3000
      - http.response_time.p95: 2000
scenarios:
  - flow:
      - get:
          url: "/"
      - think: 1
      - get:
          url: "/auth/login"
